### ISSUE TITLE
plugin broke after 0.6.4

### ISSUE THREAD

**Issue by CharlesChiuGit** [pengx17/logseq-plugin-heatmap#205]
After updating to 0.6.4 & 0.6.5, when I click the heatmap icon, Logseq went completely frozen until force-restart Logseq.
I also reintall the plugin, resulting the same.

Version: 0.6.4, 0.6.5
OS: win11

**Comment by pengx17** [comment]
Sorry, I am not able to reproduce the issue on my setup.
If you load a brand-new graph, will the heatmap plugin freeze your app as well?

**Comment by CharlesChiuGit** [comment]
Interestingly, If i use a new graph, it works percectly fine!
![image](https://user-images.githubusercontent.com/32497323/159876684-50b26f0e-f5e5-4898-8fc5-7227f215e644.png)

So could it be my journal was broken?

**Comment by CharlesChiuGit** [comment]
btw i often maunally delete the empty journal pages, could it be the reason why heatmap on my main graph un-usable?
![image](https://user-images.githubusercontent.com/32497323/159877373-105ebb49-347f-40e0-b148-2493d04c1eb2.png)

**Comment by pengx17** [comment]
What if you re-index your logseq_bd and try again? I think there might be some errors somewhere

**Comment by pengx17** [comment]
I also released a new version just now. In the new version, if there are any fatal errors, the heatmap panel will show a error dialog instead. 
Can you please upgrade the plugin and see if it can catch some errors for you?

**Comment by CharlesChiuGit** [comment]
I had upgrade the heatmap plugin as soon as I saw the new release, but there's no any error dialog at all.
Also I tried re-index few times, but also failed.
Next I remove all my journal files and re-index, still failed, sadly.

**Comment by pengx17** [comment]
What if you open the dev tools firstly, then open heatmap plugin and see if there are any suspicious errors in the console.log?

**Comment by CharlesChiuGit** [comment]
Sorry for the noob question, but how do i open dev tools?

**Comment by pengx17** [comment]
should be ctrl+alt+I on windows

**Comment by CharlesChiuGit** [comment]
ok, it's on. where should i look for.

**Comment by pengx17** [comment]
Thank for the info! Now that I know why the new error boundary did not work 🤪
